### ISSUE TITLE
Don't store project picture in base64 inside of MongoDB, prevent anything than pictures

### ISSUE THREAD

**Issue by clawfire** [smileinnovation/imannotate#46]
Maybe you should consider using MongoDB GridFS for the project pictures.

Also, you could use HTML attributes of the input field to prevent any other type than a picture to be uploaded (I tried, and uploaded a Mac App 😆).

**Comment by metal3d** [comment]
And if we want to use it as a app store ? :smile: 

I'm currently creating the image storage connector to be able to store images on S3, FS, whatever we want... (as for the picture provider, it's modulable)

This is for the V2

**Comment by metal3d** [comment]
Just to ensure that nobody can think that we store image in MongoDB => We don't. The image URL is stored in memory (or any memory module as Redis), and the image is only proxified by the API. At this time, we don't store image (it's comming)

**Comment by metal3d** [comment]
Ok I just understand that you were speaking about picture of the project, not the pictures that are annotated.

**Comment by clawfire** [comment]
yep.

and my point about not filtering the input is then an important one
