### ISSUE TITLE
drawing box at the edge of pictures

### ISSUE THREAD

**Issue by clawfire** [smileinnovation/imannotate#47]
![](https://cl.ly/4a2ae12e6f3a/Screen%252520Recording%2525202019-02-11%252520at%25252006.49%252520PM.gif)

As you can see here, there's an issue preventing us to draw box on the edge of the picture. I think that's the limit of the canva element but, maybe then you should have like 20px around the picture you are loading in the canva to let us draw on the edge of the picture.

**Comment by metal3d** [comment]
Weird, I can draw border on the edge.

(let the gif to load)

![border](https://user-images.githubusercontent.com/100080/52652016-92691d80-2eed-11e9-8d9f-2d611fa99fd9.gif)

The fact is that if you go out the canvas, so the "mousemove" event is not raised on the target element, and we can't continue to draw as we don't have coordinates of the event. This is a browser limitation, and I really don't have any idea on how to fix that.

But I can draw borders on the picture's edge.

**Comment by metal3d** [comment]
Note: I don't see your preview, I only see a blank space on your comment:

![image](https://user-images.githubusercontent.com/100080/52652316-32bf4200-2eee-11e9-8c41-86cb18cc080e.png)

**Comment by clawfire** [comment]
> Note: I don't see your preview, I only see a blank space on your comment:
> 
> ![image](https://user-images.githubusercontent.com/100080/52652316-32bf4200-2eee-11e9-8c41-86cb18cc080e.png)

works on my side ... I just used the upload function of github to upload a gif

**Comment by metal3d** [comment]
As I did, but mine is displayed :p

**Comment by clawfire** [comment]
> As I did, but mine is displayed :p

Seems an issue on your side then ... :D 

So, my point is more like it's difficult to draw a border on the edge of the picture if the movement of the mouse isn't tracked anymore when I go over the picture border. I totally understand the limitations of the canvas element, that's why I suggested to not use 100% of the canvas for the picture but let a few extra pixels to make it easier to use

**Comment by metal3d** [comment]
https://camo.githubusercontent.com/14cc80467295550c0cd3434191ef760456e2e51a/68747470733a2f2f636c2e6c792f3461326165313265366633612f53637265656e253235323532305265636f7264696e6725323532353230323031392d30322d31312532353235323061742532353235323030362e343925323532353230504d2e676966 

Content length expected

**Comment by clawfire** [comment]
![68747470733a2f2f636c2e6c792f3461326165313265366633612f53637265656e253235323532305265636f7264696e6725323532353230323031392d30322d31312532353235323061742532353235323030362e343925323532353230504d2e676966](https://user-images.githubusercontent.com/1178/52653522-64390d00-2ef0-11e9-91f4-acc80ffa3a84.gif)

**Comment by metal3d** [comment]
@clawfire  = > Is that OK for you ? If yes, I will push a PR that you can review.

![new-border](https://user-images.githubusercontent.com/100080/52660902-04972d80-2f01-11e9-8280-53cd5ddc9851.gif)
