### ISSUE TITLE
Contributor cannot join annotation

### ISSUE THREAD

**Issue by heriyulianus** [smileinnovation/imannotate#57]
sorry, anyone ever found problem like this?
![selection_002](https://user-images.githubusercontent.com/28983232/53144306-52312b80-35ce-11e9-9d88-07a697c22647.png)

**Comment by metal3d** [comment]
Hi, and thanks for the issue.
I will take a look, but the test I made didn't reveal me that problem. Can you please give a bit more details on how the account were created and added to the project ?
Are you launching Imannotate in "dev" mode (make dev), or in production mode (make) ?

**Comment by hervz** [comment]
oh im sorry, thanks for reply, i created two account, the first one has a project (owner) and the second one has no project (contributor), so i add the second account from the first account through project form (at the very bottom option). I am running in dev mode using make dev. and when i want to annotate from second account (contributor), it gave me the error as the picture above. actually i am also wondering about "isadmin", when i navigate to admin dashboard and click the 'users', i didnt see any button to add "admin". am i right *ngFor="let stat of stats" isn't working?

**Comment by metal3d** [comment]
Thanks, I will take a look in a couple of minutes.

At this time, we only create one admin user. We will allow the change in the admin dashboard later (that's not a complex feature, but we also work on major changes)

For the `ngFor`, this is another issue ? Where do you have this problem ?

**Comment by hervz** [comment]
No, i am just wondering that i didnt see any user appear in admin dasboard
"users", i think it related to "ngFor=let stat of stats" doesnt run well.
Thank you so much for helping me. I am also still searching on how to solve
the contributor problem

**Comment by metal3d** [comment]
OK, just tried to add a contributor on a project and it seems to work here... It may be another problem, when you begin to type the name of the contributor, have you clicked on the name in the list or have you only typed the name ? It can be a simple problem on ID injection in the form. If yes, so I can try to force the selection.

Try to add a contributor by clicking in the list that may appear when you begin to type the name.

For the admin view, please create another issue so I can close that one and take a look on the other in a second time.

**Comment by metal3d** [comment]
mmmh. actually adding the name only without to click works as well here...

![imannotate-add-remove-contributors](https://user-images.githubusercontent.com/100080/53237706-a0f6c800-3697-11e9-914d-4f1cd581e5fa.gif)

**Comment by hervz** [comment]
Yes i just type a name and then click the name when it shows up. The
project that i was created in owner account appear in the dasboard, but
when i click annotate in the miniview, it shows blank, it says "next image"
and has no authorized

**Comment by metal3d** [comment]
ah ! ok !!!
Right, I've got it, I'm checking the problem. Thanks a lot

**Comment by hervz** [comment]
Can your second account annotate any image? It says the second account has
n o authorized

**Comment by hervz** [comment]
Thank you for your help, it has already two weeks since i searched how to
solve it. But still didnt find it

**Comment by metal3d** [comment]
Ok - I really wonder how I could leave that mistake, but the function that authorize contributor to see next image was always returning "false".

I pushed the fix, you can "pull" the master branch and make a test. Sorry for that...

**Comment by hervz** [comment]
Sorry for late reply, may i know where is exactly the problem? Is it from
api?

**Comment by metal3d** [comment]
You can check the commit that is notified in that issue, right above

https://github.com/smileinnovation/imannotate/commit/61ba97da6f9ec8386415ca6e820edaf8e0c3b981

**Comment by hervz** [comment]
Oh okay, i will check soon. Thank you very much
