### ISSUE TITLE
docker-compose in daemon mode "-d"

### ISSUE THREAD

**Issue by GuillaumeMathieu27140** [smileinnovation/imannotate#61]
**Describe the bug**
In prod mode at least, could you please run docker-compose in daemon mode "-d" ?

**To Reproduce**
1. Git clone project
2. Go to created folder
3. make prod

**Desktop:**
 - OS: centos 7

**Project (please complete the following information):**
 - Imannotate version: master

**Comment by roychowdhuryrohit-dev** [comment]
`[GIN-debug] Listening and serving HTTP on :8000`
After this, I am going to localhost:8000 but nothing shows up. I am using Safari on MacOS.

**Comment by GuillaumeMathieu27140** [comment]
Hello @roychowdhuryrohit-dev 
After make prod, ui service seems to be available on 8080 port, not 8000 as mention in documentation.
