### ISSUE TITLE
Minio as S3 Storage Option

### ISSUE THREAD

**Issue by Rodri9o** [smileinnovation/imannotate#80]
Dear Smile Innovation Team,

Thanks for such awesome software.
Is it possible to specify an S3-compatible object storage solution other than AWS S3?

![image](https://user-images.githubusercontent.com/9559297/85621914-0d8b2980-b634-11ea-8850-8157febfe7a3.png)

I am running a Minio Cluster (as described below) but I am unable to connect to it from the IMANNOTATE Web Ui. 
https://docs.min.io/docs/deploy-minio-on-docker-swarm) 

Any pointer would be greatly appreciated.
Cheers,
/R

**Comment by metal3d** [comment]
That's weird, I was able to use minio during the development phase. I will take a look as soon as I can (I'm very busy these days)

Note that we're studying a rewrite on some strong parts of the tool + upgrade dependencies, so keep in touch :)

**Comment by Rodri9o** [comment]
> 
> 
> That's weird, I was able to use minio during the development phase. I will take a look as soon as I can (I'm very busy these days)
> Note that we're studying a rewrite on some strong parts of the tool + upgrade dependencies, so keep in touch :)

Hey @metal3d - Thanks for the response. 

![image](https://user-images.githubusercontent.com/9559297/86435934-26987800-bccf-11ea-92cb-f757160b8c75.png)

Hence my feature request for "Minio S3" support.

**Comment by metal3d** [comment]
I forget to mention that us-west-1 should work !

**Comment by Rodri9o** [comment]
I'll give it a shot. 
But not sure how the application would know to search my Minio S3 bucket  versus AWS S3 (drop-down).
Thank you, @metal3d.

**Comment by metal3d** [comment]
Oh yes, right... There is no field to give the minio endpoint.

I will take some times very soon to make updates. Sorry for that.
